services:
  - docker
language: generic
env:
  matrix:
    - ROS_DISTRO="kinetic" OS_CODE_NAME="xenial"
    - ROS_DISTRO="melodic" OS_CODE_NAME="bionic"
install:
  - git clone --quiet --depth 1 https://github.com/ros-industrial/industrial_ci.git .industrial_ci -b master
script:
  - .industrial_ci/travis.sh
